name: Build and Deploy NestJS App to ECS

on:
    push:
        branches:
        - main

env:
  ECR_IMAGE: ${{vars.ECR_IMAGE}}
  AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}
# ECS_CLUSTER: ${{vars.ECS_CLUSTER}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{env.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_DEFAULT_REGION}}.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t ${{env.ECR_IMAGE}} .
          docker push ${{env.ECR_IMAGE}}

#      - name: Deploy to ECS
#        run: |
#          aws ecs update-service --cluster ${{env.ECS_CLUSTER}} --service ${{env.ECS_SERVICE}} --force-new-deployment